### ISSUE TITLE
Update README to explain new build procedure

### ISSUE THREAD

**Issue by DocSavage** [janelia-flyem/dvid-console#1]
The current barebones README should be updated to reflect the new build procedure -- how one goes about getting a nice static website directory that can be used as an option to the "dvid serve" command.

**Comment by mmorehea** [comment]
The readme should contain information on building the gruntfile from scratch, or should indicate that the prebuilt version can be pulled via the release section.

Currently, for the uninitiated, the readme reads as if you could just clone this repo and use it immediately.

**Comment by neomorphic** [comment]
The README has been updated in a5b0dd7552861 to show the quick way and the developer way to build and use the console
