### ISSUE TITLE
Node UUID text size out of whack

### ISSUE THREAD

**Issue by DocSavage** [janelia-flyem/dvid-console#13]
The UUID text label for each node is too large for the node in MB-6 (emdata1:8500).  It's possible that this occured when I zoomed in to see the DAG.

**Comment by neomorphic** [comment]
Unable to replicate. Can you add a screenshot?

**Comment by DocSavage** [comment]
Here's a grab from my Chrome version 44.0.2403.130 (64-bit) on MacOS 10.9.5.
![bad_dag_formatting](https://cloud.githubusercontent.com/assets/185/9308141/5c31dcd0-44d0-11e5-9dcb-282dc34e2213.png)

**Comment by neomorphic** [comment]
That looks bad. I am using the same version of chrome, but can't replicate it. Maybe I can stop by and look at your machine. Might be specific to you?

**Comment by neomorphic** [comment]
Have you got a user stylesheet that is overriding the font size of <text> nodes?

**Comment by DocSavage** [comment]
nHere's what I get on the javascript console for the browser:
ReferenceError: A store named a already exists, double check your store
names or pass in your own custom identifier for each store
    at Object.e [as warn] (
http://emdata1.int.janelia.org:8500/js/bundle.min.js:5:2723)
    at a.k.value (
http://emdata1.int.janelia.org:8500/js/bundle.min.js:4:22804)
    at Object.28.../actions/LogActions (
http://emdata1.int.janelia.org:8500/js/bundle.min.js:4:13010)
    at e (http://emdata1.int.janelia.org:8500/js/bundle.min.js:2:254)
    at http://emdata1.int.janelia.org:8500/js/bundle.min.js:2:305
    at Object.18.../actions/LogActions (
http://emdata1.int.janelia.org:8500/js/bundle.min.js:3:278)
    at e (http://emdata1.int.janelia.org:8500/js/bundle.min.js:2:254)
    at http://emdata1.int.janelia.org:8500/js/bundle.min.js:2:305
    at Object.16.../actions/ServerActions (
http://emdata1.int.janelia.org:8500/js/bundle.min.js:2:25010)
    at e (http://emdata1.int.janelia.org:8500/js/bundle.min.js:2:254)

I'll try to delete caches.  Maybe it's cached some javascript that was an
older version of the library and is holding onto it even after it's been
updated upstream.

**Comment by DocSavage** [comment]
Deleting cache and even opening it in incognito window makes no difference.

**Comment by neomorphic** [comment]
I managed to replicate the text size, but only by modifying the stylesheet in the developer console. It seems something else is changing it on your browser.

**Comment by DocSavage** [comment]
After some testing, it looks like this is a second monitor issue.  If the browser is dragged from the MacBook Pro screen (font OK) to the second monitor, the font for the nodes will increase incorrectly.  This problem occurs for MacBook Pro with MacOS X 10.9, but not MacOS X with 10.10, which suggests it might be OS version specific.

**Comment by DocSavage** [comment]
There are still errors after upgrading to El Capitan.  Now I can't even see DAG.  Image of errors in javascript console attached.
![bad_dvid_console](https://cloud.githubusercontent.com/assets/185/12688783/75be4fb4-c6a6-11e5-9ec8-633e5f4b159e.png)

**Comment by neomorphic** [comment]
This is because Chrome deprecated and then removed a function that the dagre-d3 code relies on to draw the connection lines. I am looking for a patch, but nothing is working so far.

**Comment by neomorphic** [comment]
Release 1.11.1 fixes this by updating the version of the dagre-d3 library.
