### ISSUE TITLE
Space missing in "about" page

### ISSUE THREAD

**Issue by DocSavage** [janelia-flyem/dvid-console#18]
When I look at the about page on the console for emdata1, I see the following:

    DVID documentation can be found on githubas well as the automatically updated Go Doc documentation.

Note the lack of space between the "github" link and the following "as".

The code is here:
https://github.com/janelia-flyem/dvid-console/blob/master/js/components/About.react.js#L27

Strangely, there is some whitespace after the link tag, so is this an artifact of the minimization process?

**Comment by neomorphic** [comment]
It appears that it is an intentional change in react:

https://facebook.github.io/react/blog/2014/02/16/react-v0.9-rc1.html#upgrade-notes

**Comment by neomorphic** [comment]
Issue fixed in 07a40ae00f
