### ISSUE TITLE
Commit message not showing up in DAG

### ISSUE THREAD

**Issue by DocSavage** [janelia-flyem/dvid-console#24]
After adding a few descendent versions, I'm unable to see a commit message on mouseover of a node (f5052) on the right of the DAG for AL-7 on tem-dvid.int.janelia.org:7400.  I was able to see it earlier, so not sure if this is a browser issue or problem with the code.  I'm running most recent Google Chrome [Version 46.0.2490.86 (64-bit)] on Mac 10.9.5.

**Comment by neomorphic** [comment]
After investigation it looks like the DVID API was not returning a note for f5052. This means the DAG is not able to show a note. There is a potential that the note was removed from the server, but we were unable to figure out how that could have happened.
