### ISSUE TITLE
Lack of new repository button in an empty dvid installation

### ISSUE THREAD

**Issue by quinnkjones** [janelia-flyem/dvid-console#26]
![selection_025](https://cloud.githubusercontent.com/assets/5806061/14297635/e44d3c20-fb4d-11e5-914e-3c049fda7c2c.png)
See above image, it's definitely not a critical issue since I will just create the repo using the command line tool next, but I thought I'd let you know.

Webkit info: 
WebKit version	537.36
Browser name	Google Chrome 49.0.2623.110
Google Chrome version	49.0.2623.110
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by neomorphic** [comment]
The button has been hidden by request of the management. It was decided that we didn't want to expose admin features to general users without an authentication system in place. If you really want to see it, add ?admin=1 to the end of the url.
