### ISSUE TITLE
README note about dvid -webclient argument doesn't seem to work

### ISSUE THREAD

**Issue by grisaitis** [janelia-flyem/dvid-console#40]
The README says I can provide a `-webclient` flag when I start the `dvid` command... But this doesn't seem to work:

`dvid -verbose -webclient=/path/to/unpacked/dvid-console serve /path/to/dvid/data`

When I try this, I get `flag provided but not defined: -webclient`

Is this an issue with dvid - where it definitely should have this flag, but it's not working - or is this README out of sync with dvid? 

If dvid is fine, what's the best way to specify the web client now?

**Comment by neomorphic** [comment]
Hi @grisaitis ,

Can you make sure you are using '--webclient=/path' the double dash is important. If that is still not working it is most likely an issue with dvid and should be logged in the dvid repo issue tracker.

**Comment by grisaitis** [comment]
I added double dashes and got the same result. :/

I just realized that my config.toml file _also_ specifies the web client location... but this doesn't seem to work either. I can confirm that the repo is cloned to the directory specified in the toml file, or in the `--webclient` flag when i do specify it.

**Comment by neomorphic** [comment]
Can you post your .toml file?

**Comment by grisaitis** [comment]
```
[server]
httpAddress = "0.0.0.0:8000"
rpcAddress = "0.0.0.0:8001"
webClient = "/usr/local/dvid-console"

# How new data instance ids are generated.
# Is one of "random" or "sequential".  If "sequential" can set "start_instance_id" property.
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.

[logging]
logfile = "/data/logs/dvid.log"
max_log_size = 500 # MB
max_log_age = 30   # days

[store]   
    # if no store.metadata is provided, it defaults to store.mutable configuration
    [store.default]
    engine = "basholeveldb"
    path = "/var/dvid/db"
```

**Comment by grisaitis** [comment]
The debug logs in my browser says that bundle.js can't be found. Does the js need to be built before serving?

**Comment by neomorphic** [comment]
If you are using the released version from the releases tab, then you should have the bundle,js file already. If you are checking the code out from the repo, then you will have to build the bundle file using node.

**Comment by neomorphic** [comment]
Check the .  "[For Developers](https://github.com/janelia-flyem/dvid-console#for-developers)"  section of the README for instructions on building

**Comment by DocSavage** [comment]
It appears the "webclient" option was removed from the command line dvid when it was moved to the TOML file.  I'll update the dvid documentation.

**Comment by DocSavage** [comment]
README was updated in commit 64c7ad2.  Thanks.
