### ISSUE TITLE
Creating data with syncing does not seem to work

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid-console#42]
I tried to create an annotation data with other data instances selected in the sync list. But the new data instance is not synced correctly. Not sure if I did anything wrong. 
Another suggestion: it will be appreciated that any function that does not work as expected can be removed until it's fixed. It has caused some troubles for me, at least for a couple of times.

**Comment by westona** [comment]
@tingzhao are all of these other functions that don't work documented? If not, could you help us by either letting us know what's broken or submitting bug requests?
I'll have time soon to work on bug fixes for flyem projects :).

**Comment by tingzhao** [comment]
This is the one I just found out. There was a bug with version before, but I believe that's fixed.

**Comment by DocSavage** [comment]
@tingzhao Is this a problem with the console not correctly setting up a sync (which can be gleaned by doing a GET /info and checking the annotation instance's syncs), or another bug like the annotations not necessarily getting denormalized, which is a DVID bug?  I think you've spotted an issue with some annotations not properly getting retrieved from their label.

**Comment by tingzhao** [comment]
It's more likely to be a console bug because I can create syncs by posting to http api directly.
