### ISSUE TITLE
Tile viewer launch

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid-console#5]
Please launch the viewer by choosing the center of the segmentation bounding box.

**Comment by neomorphic** [comment]
I am unclear where the segmentation bounding box is stored. Is it the MinIndex, MaxIndex values in the label info JSON?

**Comment by stephenplaza** [comment]
Correct.  In the future it would be nice to specify an 'ROI' as well but you can use the min and max.

**Comment by neomorphic** [comment]
Fixed in commit 3fb2659ffa98e
