### ISSUE TITLE
Distribution bundle download links are missing

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid-console#51]
The dvid-console [releases page on github](https://github.com/janelia-flyem/dvid-console/releases/) allows me to download zip/tar files of the source code for the most recent tag, but there is no link for the fully-packaged release bundle for distribution.

Old releases used to provide the pre-built distribution bundle.  (I'm not sure how to make that appear on Github; @neomorphic could probably explain.)  For reference, the most recent "complete" release was [1.14.10](https://github.com/janelia-flyem/dvid-console/releases?after=v2.0.1).

On a related note, it looks like the `dist` folder was accidentally committed to this repo 6 months ago.  IIUC, `dist` is a build product and is not supposed to be committed into the repository.  I suppose it ought to be removed.

**Comment by ntj** [comment]
@stuarteberg , we published a new release v2.1.4 and it contains the pre-built tar.gz file and the dist folder is gone from the repository as well.
