### ISSUE TITLE
dvid-console is confused by external ssl termination

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/dvid-console#52]
Hi,
One of my DVID installs uses nginx in front for SSL termination; the head of my config has the hostname, the httpAddress is set to 0.0.0.0:8001
I am exposing DVID over both http and https with nginx in front. My nginx config looks like this:

```
proxy_cache_path /var/raid/dvid/dvid-cache levels=1:2 keys_zone=dvid_cache:100m max_size=10g inactive=1h use_temp_path=off;

server {
        listen 80 default_server;
        #listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm;
        server_name SITE;

        location / {
          proxy_ignore_headers Cache-Control;
          proxy_buffering on;
          proxy_cache_valid 200 1h;
          proxy_cache dvid_cache;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://127.0.0.1:8000/;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/SITE/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/SITE/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

The issue that I'm seeing is that when viewed over http, everything works fine (the admin page shows 1 repo, all the cores, the server uptime, and so on). When viewed over https, the console app is very confused showing "0 out of 0" cores, 0 repos, 0s server uptime, and so on. If I tell my browser to "load unsafe scripts" it works.

I believe this could be fixed by having the web app figure out whether it's talking http or https and make requests of the same sort, so as to allow for nicer SSL termination behaviour.

This isn't a major pain point for us (we rarely use the DVID console, and the DVID web API calls all work fine over https).

**Comment by neomorphic** [comment]
@pgunn, I forgot to ask, which version of the console are you running?

**Comment by pgunn** [comment]
This is an issue with 3.1.0

**Comment by neomorphic** [comment]
This is fixed in version 3.1.1 and commit f26b50c53d. There is a new release under the releases tab.

**Comment by pgunn** [comment]
The main console works now, but the data viewer does not; there's some URL translation logic in there that might need to be updated.

Error message cannot be cut'n'pasted (the dismissable dialogue in there is not selectable) but it's something like this:

```Error retrieving metadata for volume dvid://https//waspem-dvid.OURDOMAIN.org:/.....: Invalid DVID URL: "https//waspem-dvid.OURDOMAIN.org:/e0c77...". ```

I'm guessing the missing colon after https in the second is the problem.

**Comment by neomorphic** [comment]
Thanks for the feedback. I have fixed those issues and added some tests to cover the url generation. This should prevent further issues. You can find an updated version here: 

https://github.com/janelia-flyem/dvid-console/releases/tag/3.1.2
