### ISSUE TITLE
Make neuroglancer view full-screen

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid-console#53]
The neuroglancer view does not occupy as much screen space as it could (see screenshot below).  It would be nice if the neuroglancer view were full-screen, or as close to full-screen as feasible.

cc @neomorphic 

![image](https://user-images.githubusercontent.com/1655821/57657386-3758cc80-75a9-11e9-9a7b-70d093109b72.png)

**Comment by neomorphic** [comment]
Fixed in release 3.4.0
