### ISSUE TITLE
Feature Request: Sort data instances in list

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/dvid-console#56]
Currently the list of data instances is not sorted. This feature request is to alphabetically sort them, to make it faster to see if a given instance is present in the repo.

**Comment by neomorphic** [comment]
@pgunn , currently they are sorted by Type, eg: annotation, keyvalue, labelmap and then within those groupings, they are sorted alphabetically. I will investigate adding an alternative sort switch
